config/routes.rb
Tiramisu::Application.routes.draw do

  get 'logout'  => 'sessions#destroy', :as => 'logout'
  get 'login'   => 'sessions#new', :as => 'login'
  get 'signup'  => 'users#new', :as => 'signup'
  
  resources :users
  resources :sessions
  resources :password_resets
  resources :projects do
    post 'comments' => 'comments#create', :as => 'comments'
    get  'comments/:id/edit' => 'comments#edit', :as => 'edit_comment'
    put  'comments/:id' => 'comments#update', :as => 'comment'
    delete 'comments/:id' => 'comments#destroy'
  end

  post '/projects/:id/promote' => 'projects#promote', :as => 'promote_project'
  post '/projects/:id/pledge'  => 'projects#pledge', :as => 'pledge_project'
  post '/projects/:id/leave'   => 'projects#leave', :as => 'leave_project'

  get '/moderate' => 'projects#moderate', :as => 'moderate'
  post '/projects/:id/approve' => 'projects#approve', :as => 'approve_project'

  get '/:username/projects' => 'users#projects', :as => 'user_projects'
  get '/settings' => 'users#edit', :as => 'user_settings'

  root :to => 'projects#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user
  belongs_to :project
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login
  before_filter :must_be_creator, :except => [:create]

  def create
    @comment = Comment.new(params[:comment])
    @comment.project_id = params[:project_id]
    @comment.user = current_user

    if @comment.save
      CommentMailer.comment_email(@comment).deliver
      redirect_to @comment.project, :notice => 'Comment saved!'
    else
      redirect_to @comment.project, :alert => 'Could not save comment'
    end
  end

  def edit
    #@comment = Comment.find(params[:id])
  end

  def update
    #@comment = Comment.find(params[:id])

    if @comment.update_attributes(params[:comment])
      redirect_to @comment.project, :notice => 'Comment updated!'
    else
      redirect_to @comment.project, :alert => 'Could not update comment'
    end
  end

  def destroy
    #@comment = Comment.find(params[:id])

    if @comment.destroy
      redirect_to @comment.project, :notice => 'Comment deleted'
    else
      redirect_to @comment.project, :alert => 'Comment could not be deleted'
    end
  end

  private

  def must_be_creator
    @comment = Comment.find(params[:id]) # notice how we set @project here, and don't need to do it later
    return if current_user_admin?
    redirect_to @comment.project, :alert => "Access Denied" unless @comment.user == current_user
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <div class="leftcol">
    <a href="<%= user_path(comment.user) %>">
      <%= image_tag gravatar_url(comment.user) %>
    </a>
  </div>

  <div class="pull-right">
    <% if current_user_admin? || comment.user == current_user %>
      <%= link_to 'Edit', project_edit_comment_path(@project, comment) %>
      <%= link_to 'Destroy', project_comment_path(@project, comment), :method => :delete, :confirm => 'Are you sure?' %>
    <% end %>
  </div>

  <div class="rightcol">
    <div class="comment-user">
      <b><%= link_to comment.user.username, comment.user %></b>
    </div>

    <div class="comment-body"><%= markdown comment.content %></div>
  </div>
  <div class="clear"></div>
<% end %>

app/views/comments/_form.html.erb
<% # TODO: this is kind of gross %>
<% #  the pair is generated dynamically, whether we are writing a new comment, or editing one %>
<%= form_for [@project || @comment.project, @comment || @project.comments.build] do |f| %>
  <%= f.text_area :content %><br />

  <%= f.submit 'Save' %>
<% end %>

app/views/comments/edit.html.erb
<p>Edit your comment:</p>
<%= render :partial => 'form' %>