config/routes.rb
Tiramisu::Application.routes.draw do

  get 'logout'  => 'sessions#destroy', :as => 'logout'
  get 'login'   => 'sessions#new', :as => 'login'
  get 'signup'  => 'users#new', :as => 'signup'
  
  resources :users
  resources :sessions
  resources :password_resets
  resources :projects do
    post 'comments' => 'comments#create', :as => 'comments'
    get  'comments/:id/edit' => 'comments#edit', :as => 'edit_comment'
    put  'comments/:id' => 'comments#update', :as => 'comment'
    delete 'comments/:id' => 'comments#destroy'
  end

  post '/projects/:id/promote' => 'projects#promote', :as => 'promote_project'
  post '/projects/:id/pledge'  => 'projects#pledge', :as => 'pledge_project'
  post '/projects/:id/leave'   => 'projects#leave', :as => 'leave_project'

  get '/moderate' => 'projects#moderate', :as => 'moderate'
  post '/projects/:id/approve' => 'projects#approve', :as => 'approve_project'

  get '/:username/projects' => 'users#projects', :as => 'user_projects'
  get '/settings' => 'users#edit', :as => 'user_settings'

  root :to => 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :language, :long_description, :name, :user_id, :chosen
  # we don't want to allow mass-assignment for accepted, etc.

  has_many :votes, :dependent => :destroy
  has_many :pledges, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  belongs_to :user

  validates :name, :length => { :in => 5..30 }
  validates :description, :length => { :in => 5..140 }
  validates :long_description, :length => { :in => 5..3000 }
  validates :language, :length => { :in => 1..20 }

  scope :sorted_by_votes, where(:approved => true)
                          .joins(:votes)
                          .group('projects.id')
                          .order('COUNT(*) DESC')

  def promoted_by?(user)
    self.votes.where(:user_id => user).any?
  end

  def pledged_by?(user)
    self.pledges.where(:user_id => user).any?
  end

  # returns the list of emails of those who have pledged
  #   to work on the project
  # to be placed in a textarea or something
  def mailing_list
    self.pledges.collect(&:user).collect(&:email)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_login, :except => [:index, :show]
  before_filter :admin_only, :only => [:edit, :update, :moderate, :approve]
  before_filter :must_be_creator, :only => [:destroy]
  before_filter :prevent_mass_assign, :only => [:create, :update]

  def index
    @projects = Project.sorted_by_votes
  end

  def moderate
    @projects = Project.where(:approved => false)

    render 'index'
  end

  def approve
    @project = Project.find(params[:id])
    @project.approved = true
    @project.save

    redirect_to @project, :notice => 'Project has been approved!'
  end

  def show
    @project = Project.find(params[:id])
    unless current_user_admin? || @project.approved
      redirect_to projects_path, :alert => 'That project is not quite ready for the spotlight'
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    @project.user = current_user

    if @project.save
      # create a vote
      @project.votes.create(:user_id => current_user.id)

      # create a pledge
      @project.pledges.create(:user_id => current_user.id)

      # send email to admin
			ProjectsMailer.project_email(@project).deliver
			
			redirect_to root_url, :notice => "Got it! Your entry is currently waiting approval"
    else
      render :new, :alert => "An error ocurred while creating the Project"
    end
  end

  def edit
    @project = Project.find(params[:id])  
  end

  def update
    # TODO: notify user when they gain ownership of a project?
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project, :notice => "Project updated successfully"
    else
      redirect_to @project, :alert => "An error ocurred while updating the Project"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to root_url, :notice => "Project destroyed"
    else
      redirect_to @project, :alert => "An error ocurred while deleting the Project"
    end
  end

  def promote
    @project = Project.find(params[:id])

    unless @project.votes.where(:user_id => current_user).any?
      @project.votes.create(:user_id => current_user.id)
      @points = @project.votes.count
      render 'promote.js'
    else
      render :js => 'console.log("ha!")'
    end
  end

  def pledge
    @project = Project.find(params[:id])
    
    unless @project.pledges.where(:user_id => current_user).any?
      @project.pledges.create(:user_id => current_user.id)
      render 'pledge.js'
    else
      render :js => 'console.log("ha!")'
    end
  end

  def leave
    @project = Project.find(params[:id])
    if @project.pledges.where(:user_id => current_user).first.try(:destroy)
      render 'leave.js'
    else
      render :js => 'console.log("ha!")'
    end
  end

  private

  def must_be_creator
    return if current_user_admin?
    @project = Project.find(params[:id]) # notice how we set @project here, and don't need to do it later
    redirect_to @project, :alert => "Access Denied" unless @project.user == current_user
  end

  def prevent_mass_assign
    # if the user is not an admin, we remove :user_id from params
    # TODO: more modernized approach
    params[:project].delete(:user_id) unless current_user_admin?
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @project.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <br /><br />

  <% if defined?(form_type) && form_type == 'edit' %>
    <%= f.check_box :chosen %>
    <%= f.label :chosen %>

    <br /><br />
  <% end %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <br /><br />

  <%= f.label :long_description %>
  <%= f.text_area :long_description, :rows => "10" %>

  <br /><br />

  <%= f.label :language %>
  <%= f.text_field :language %>

  <br /><br />

  <% if !@project.new_record? && current_user_admin? %>
    <%= f.label :user_id, 'Owner' %>
    <%= f.select :user_id, options_for_select(User.all.map {|u| [u.username, u.id]}, @project.user_id) %>
    <br /><br />
  <% end %>

  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/projects/_project.html.erb
<%= div_for project, :class => ('chosen' if project.chosen) do %>
  <div class="numbers">
    <div class="score"><%= project.votes.count %></div>
    <div class="suffix"><%= 'vote'.pluralize project.votes.count %></div>
    <div class="promote">
      <%= link_to 'Promote', promote_project_path(project),
                  :class => 'btn btn-success' +
                    (!current_user || project.promoted_by?(current_user) ? ' disabled' : ''),
                  :remote => true, :method => :post %>
    </div>
  </div>

  <div class="body">
    <h3><%= link_to project.name, project %></h3>
    <span>A <%= project.language %> project by <%= link_to project.user.username, project.user %></span>
    <div class="info">
      <%= project.description %>
    </div>

    <div class="pledges">
      <h6><%= project.pledges.count %> <%= "pledge".pluralize(project.pledges.count) %> including</h6>
      <% project.pledges.each do |pledge| %>
        <div class="tooltipme pledge pledge_<%= pledge.user_id %>" data-title="<%= pledge.user.username %>">
          <a href="<%= user_path(pledge.user) %>">
            <%= image_tag gravatar_url(pledge.user, 40) %>
          </a>
        </div>
      <% end %>
    </div>

  </div>
  <div class="clear"></div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing <%= @project.name %></h1>

<%= render :partial => "form", :locals => { :form_type => 'edit' } %>

app/views/projects/index.html.erb
<% if @projects.empty? %>
  <p>Nothing to see here...</p>
<% end %>

<% @projects.each do |project| %>
	<%= render project %>
<% end %>

app/views/projects/leave.js.erb
$('.pledges h6').text("<%= @project.pledges.count %> <%= 'pledge'.pluralize(@project.pledges.count) %> including");
$('.pledges').find('.pledge_<%= current_user.id %>').fadeOut(250);

$('.membership a').text('Join this project');
$('.membership a').attr('href', '<%= pledge_project_path(@project) %>');

app/views/projects/new.html.erb
<p>Please enter the details for a new project</p>

<%= render :partial => "form" %>

app/views/projects/pledge.js.erb
$('.pledges h6').text("<%= @project.pledges.count %> <%= 'pledge'.pluralize(@project.pledges.count) %> including");
var new_user = $('<a></a>').addClass('pledge_<%= current_user.id %>')
                           .attr('href', '<%= user_path(current_user) %>')
                           .html('<%= image_tag gravatar_url(current_user, 40) %>')
                           .css('display', 'none');

$('.pledges').append(new_user);
$(new_user).fadeIn(250);

$('.membership a').text('Leave this project');
$('.membership a').attr('href', '<%= leave_project_path(@project) %>');

app/views/projects/promote.js.erb
$("#<%= dom_id(@project) %> .promote a").addClass('disabled');
$("#<%= dom_id(@project) %> .score").text("<%= @points %>");
$("#<%= dom_id(@project) %> .suffix").text("<%= 'vote'.pluralize(@points) %>");

app/views/projects/show.html.erb
<%= render @project %>

<div class="project push">
  <div class="numbers clear"></div>

  <div class="body">
    <% if current_user_admin? || @project.user == current_user %>
      <p><b>Mailing List</b></p>
      <div><%= @project.mailing_list.join ', ' %></div>
      <br />
    <% end %>

    <% if current_user %>
      <div class="membership">
        <% if !@project.pledged_by?(current_user) %>
          <%= link_to 'Join this project', pledge_project_path(@project),
                      :class => 'btn btn-large btn-info',
                      :remote => true, :method => :post %>
        <% else %>
          <%= link_to 'Leave this project', leave_project_path(@project),
                      :class => 'btn btn-large btn-info',
                      :remote => true, :method => :post %>
        <% end %>
      </div>
    <% end %>

    <div>
      <%= markdown @project.long_description %>
    </div>

    <% if current_user == @project.user || current_user_admin? %>
      <div class="controls">
        <% if current_user_admin? %>
          <%= link_to "Edit", edit_project_path(@project), :class => "btn btn-primary" %>
        <% end %>
        <%= link_to "Delete", @project, 
                    :method => "delete", :confirm => "Are you sure?", :class => "btn btn-danger" %>
        <% if current_user_admin? && !@project.approved %>
          <%= link_to "Approve", approve_project_path(@project),
                      :class => "btn btn-success", :method => :post %>
        <% end %>
      </div>
    <% end %>

    <!-- place comments here -->
    <h3>Showing <%= @project.comments.count %> <%= 'comment'.pluralize(@project.comments.count) %></h3>
    <% @project.comments.each do |comment| %>
      <%= render comment %>
    <% end %>

    <% if current_user %>
      <p>Post a new comment:</p>
      <%= render 'comments/form' %>
    <% end %>
  </div>
</div>

app/views/projects/vote.js.erb
$("#<%= dom_id(@project) %> .score").text(@points);
$("#<%= dom_id(@project) %> .suffix").text(<%= 'vote'.pluralize @points %>);