config/routes.rb
Tiramisu::Application.routes.draw do

  get 'logout'  => 'sessions#destroy', :as => 'logout'
  get 'login'   => 'sessions#new', :as => 'login'
  get 'signup'  => 'users#new', :as => 'signup'
  
  resources :users
  resources :sessions
  resources :password_resets
  resources :projects do
    post 'comments' => 'comments#create', :as => 'comments'
    get  'comments/:id/edit' => 'comments#edit', :as => 'edit_comment'
    put  'comments/:id' => 'comments#update', :as => 'comment'
    delete 'comments/:id' => 'comments#destroy'
  end

  post '/projects/:id/promote' => 'projects#promote', :as => 'promote_project'
  post '/projects/:id/pledge'  => 'projects#pledge', :as => 'pledge_project'
  post '/projects/:id/leave'   => 'projects#leave', :as => 'leave_project'

  get '/moderate' => 'projects#moderate', :as => 'moderate'
  post '/projects/:id/approve' => 'projects#approve', :as => 'approve_project'

  get '/:username/projects' => 'users#projects', :as => 'user_projects'
  get '/settings' => 'users#edit', :as => 'user_settings'

  root :to => 'projects#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Tiramisu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- javascript -->
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Tiramisu</a>
          <div class="nav-collapse collapse">
            <% if current_user %>
              <ul class="nav">
                <li><%= link_to "New Project", new_project_path %></li>
                <li><%= link_to "Profile", user_path(current_user) %></li>
                <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                <% if current_user_admin? %>
                  <li>
                    <a href="<%= moderate_path %>">
                      Moderate
                      <% if @moderation_count && @moderation_count > 0 %>
                        <span class="badge badge-info"><%= @moderation_count %></span>
                      <% end %>
                    </a>
                  </li>
                  <li><%= link_to "Manage Users", users_path %></li>
                <% end %>
              </ul>
              <div class="pull-right">
                <ul class="nav pull-right">
                   <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, <%= current_user.username %> <b class="caret"></b></a>
                     <ul class="dropdown-menu">
                        <li><%= link_to "Sign out", logout_path %></li>
                     </ul>
                   </li>
                </ul>
              </div>
            <% else %>
              <div class="pull-right">
                <ul class="nav">
                  <li><%= link_to "Log In", login_path %></li>
                  <li><%= link_to "Sign up", signup_path %></li>
                </ul>
              </div>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="alerts container">
      <% if flash[:alert] %>
        <div class="alert alert-error">
          <%= flash[:alert] %>
          <button type="button" class="close" data-dismiss="alert">×</button>
        </div>
      <% end %>

      <% if flash[:notice] %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
          <button type="button" class="close" data-dismiss="alert">×</button>
        </div>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>